import type { Metadata } from "next";
import { Schibsted_Grotesk , Martian_Mono } from "next/font/google";
import "./globals.css";
import LightRays from "@/components/ui/LightRays";
import Navbar from "@/components/ui/Navbar";
const schibstedGrotesk = Schibsted_Grotesk({
  variable: "--font-schibsted-grotesk",
  subsets: ["latin"],
});

const martianMono = Martian_Mono({
  variable: "--font-martian-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eventaoy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen ${ schibstedGrotesk.variable} ${martianMono.variable} antialiased`}
      >
        <Navbar />
        <div className="absolute inset-0 -z-10 w-full h-full">
        <LightRays 
          raysOrigin="top-center-offset"
          raysColor="#5dfeca"
          raysSpeed={0.5}
          lightSpread={0.8}
          rayLength={1.4}
          followMouse={true}
          mouseInfluence={0.03}
          // saturation={1.0}
          noiseAmount={0.1}
          distortion={0.02}
          />
        </div>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
